const routes = {
  home: '/',
  minimal: '/minimal',
  retro: '/retro',
  swap: '/swap',
  liquidity: '/liquidity',
  liquidityPosition: '/liquidity-position',
  farms: '/farms',
  farmsTwo: '/farms-2',
  createNft: '/create-nft',
  search: '/search?view=coleccion',
  notification: '/notification',
  vote: '/vote',
  proposals: '/proposals',
  createProposal: '/proposals/create',
  charts: '/charts',
  profile: '/profile',
  portfolio: '/profile?view=inversiones',
  history: '/profile?view=staking',
  classic: '/classic',
  createuser: '/createuser',
  staking: '/staking',
  principal: '/principal',
  details: '/details',
  academiaX: '/details/PA',
  alphaR: '/details/AP',
  investingV: '/details/IV',
  coaching: '/details/NC',
  podcast: '/details/PS',
  cg: '/details/CG',
  comunidad: '/productos',
  inversion: '/inversiones',
  _profile: '/frenchies',
  cien: '/details/100',
  unK: '/details/1K',
  cincoK: '/details/5K',
  diezK: '/details/10K',
  veinteK: '/details/20K',
  cincuentaK: '/details/50K',
  cienK: '/details/100K',
};

export default routes;
